<?php

/** @var \Amici\BannerSlider\Block\Adminhtml\Slider\AssignBanners $banner */

/** @var \Amici\BannerSlider\Block\Adminhtml\Slider\Tab\Banner $bannerGrid */
$bannerGrid = $block->getBannerGrid();
$gridJsObjectName = $bannerGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<input type="hidden" name="slider_banners" id="in_slider_banners" data-form-part="amici_slider_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "Amici_BannerSlider/amici/slider/assign-banners": {
                "selectedBanners": <?= /* @noEscape */ $block->getBannersJson(); ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
